############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Experience"
url = "experience/"
weight = 3

[[main]]
name = "Projects"
url = "projects/"
weight = 4

[[main]]
name = "Hobbies"
url = "hobbies/"
weight = 5

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

